### ISSUE TITLE
SESSION ISSUE ON AZURE

### ISSUE THREAD

**Issue by Kendysond** [ScottHelme/codeigniter-azure-session-handler#1]
PLEASE I'VE BEEN GETTING THE ERROR "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." ON ALL MY PAGES AND I BELIEVE ITS THE SESSION THAT IS CAUSING IT,PLEASE WHERE DO I PUT THIS YOUR PLUGIN AND CAN YOU PLEASE JUST GIVE ME A SHORT TUTORIAL ON HOW TO USE IT 
THANK YOU IN ADVANCE.

**Comment by ScottHelme** [comment]
I have a blog coming shortly on how to use Azure Table Storage as a PHP session store. Keep an eye on https://scotthelme.co.uk for more details.
